### ISSUE TITLE
出现Error: spawnSync /bin/sh ENOENT 的错误

### ISSUE THREAD

**Issue by heguangzhi** [arielyang/phabricator_zh_Hans#5]
h-3.2# bin/compile
------------------------------
Switch branch of ../phabricator to stable.
child_process.js:656
    throw err;
    ^

Error: spawnSync /bin/sh ENOENT
    at Object.spawnSync (internal/child_process.js:990:20)
    at spawnSync (child_process.js:601:24)
    at Object.execSync (child_process.js:648:13)
    at getGitInfo (/Users/guangzhihe/Work/phabricator_zh_Hans/bin/compile:362:32)
    at Object.<anonymous> (/Users/guangzhihe/Work/phabricator_zh_Hans/bin/compile:36:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)

**Comment by arielyang** [comment]
和 phabricator_zh_Hans 目录同级下要存在 phabricator 和 libphutil 两个项目。

地址：
https://github.com/phacility/phabricator.git
https://github.com/phacility/libphutil.git

**Comment by arielyang** [comment]
或者你拉下最新版本，刚优化了这个问题，如果这两个 repo 不存在，自动 clone 下来。

**Comment by heguangzhi** [comment]
好的 ，我试试。 多谢！

**Comment by heguangzhi** [comment]
可以了 没有问题了
